Spi update
Ecam-Eurobot/Tutorials pull request #26
Opened 2018-05-10 19:49 UTC by Sellto

no comment.

2018-05-10 22:23 UTC, azerupi commented on src/electronics/communication/communication.md
> +##This section aims to show how different communication techniques have been implemented
You forgot the spaces between the hashtags and your titles 😉

2018-05-11 06:38 UTC, bluebeel requested changes
Espace

2018-05-11 06:38 UTC, bluebeel commented on src/electronics/communication/i2c.md
> +#I2C
Espace :)

2018-05-11 06:38 UTC, bluebeel commented on src/electronics/communication/spi.md
> +#Just for curious
Espace

2018-05-11 06:41 UTC, azerupi approved these changes

2018-05-11 06:42 UTC, Sellto commented
here you are :)

2018-05-11 06:47 UTC, bluebeel commented on src/electronics/communication/spi.md
> +#Just for curious
Espace?

2018-05-11 06:49 UTC, bluebeel requested changes
Espace line 219

2018-05-11 08:19 UTC, bluebeel approved these changes

2018-05-11 08:19 UTC, merged